// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/focus" | "/reader/challenge" | "/reader/page" | "/reader/rub" | "/settings" | "/stats" | "/tafsir" | "/tafsir/[verseKey]"
type AppRouteHandlerRoutes = "/api/chapter_index" | "/api/offline-quran" | "/api/page" | "/api/page_recitation" | "/api/page_word_timings" | "/api/recitations" | "/api/rub" | "/api/rub_recitation" | "/api/rub_word_timings" | "/api/set_rub" | "/api/status" | "/api/surah_challenge" | "/api/tafsir" | "/api/verse_audio" | "/api/verse_sequence"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/chapter_index": {}
  "/api/offline-quran": {}
  "/api/page": {}
  "/api/page_recitation": {}
  "/api/page_word_timings": {}
  "/api/recitations": {}
  "/api/rub": {}
  "/api/rub_recitation": {}
  "/api/rub_word_timings": {}
  "/api/set_rub": {}
  "/api/status": {}
  "/api/surah_challenge": {}
  "/api/tafsir": {}
  "/api/verse_audio": {}
  "/api/verse_sequence": {}
  "/focus": {}
  "/reader/challenge": {}
  "/reader/page": {}
  "/reader/rub": {}
  "/settings": {}
  "/stats": {}
  "/tafsir": {}
  "/tafsir/[verseKey]": { "verseKey": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
