// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/focus/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/focus">> = Specific
  const handler = {} as typeof import("../../src/app/focus/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reader/challenge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reader/challenge">> = Specific
  const handler = {} as typeof import("../../src/app/reader/challenge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reader/page/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reader/page">> = Specific
  const handler = {} as typeof import("../../src/app/reader/page/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reader/rub/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reader/rub">> = Specific
  const handler = {} as typeof import("../../src/app/reader/rub/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/stats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stats">> = Specific
  const handler = {} as typeof import("../../src/app/stats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tafsir/[verseKey]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tafsir/[verseKey]">> = Specific
  const handler = {} as typeof import("../../src/app/tafsir/[verseKey]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tafsir/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tafsir">> = Specific
  const handler = {} as typeof import("../../src/app/tafsir/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/chapter_index/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chapter_index">> = Specific
  const handler = {} as typeof import("../../src/app/api/chapter_index/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/offline-quran/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/offline-quran">> = Specific
  const handler = {} as typeof import("../../src/app/api/offline-quran/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/page/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/page">> = Specific
  const handler = {} as typeof import("../../src/app/api/page/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/page_recitation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/page_recitation">> = Specific
  const handler = {} as typeof import("../../src/app/api/page_recitation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/page_word_timings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/page_word_timings">> = Specific
  const handler = {} as typeof import("../../src/app/api/page_word_timings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recitations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recitations">> = Specific
  const handler = {} as typeof import("../../src/app/api/recitations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/rub/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rub">> = Specific
  const handler = {} as typeof import("../../src/app/api/rub/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/rub_recitation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rub_recitation">> = Specific
  const handler = {} as typeof import("../../src/app/api/rub_recitation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/rub_word_timings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rub_word_timings">> = Specific
  const handler = {} as typeof import("../../src/app/api/rub_word_timings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/set_rub/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/set_rub">> = Specific
  const handler = {} as typeof import("../../src/app/api/set_rub/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/surah_challenge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/surah_challenge">> = Specific
  const handler = {} as typeof import("../../src/app/api/surah_challenge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tafsir/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tafsir">> = Specific
  const handler = {} as typeof import("../../src/app/api/tafsir/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/verse_audio/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/verse_audio">> = Specific
  const handler = {} as typeof import("../../src/app/api/verse_audio/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/verse_sequence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/verse_sequence">> = Specific
  const handler = {} as typeof import("../../src/app/api/verse_sequence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
